# !/usr/bin/env python
# coding=utf8
# Author: quheng

"""
定义语句类型
"""

program = 'program'
program_head = 'program_head'
routine = 'routine'
sub_routine = 'sub_routine'
routine_head = 'routine_head'
label_part = 'label_part'
const_part = 'const_part'
const_expr_list = 'const_expr_list'
const_value = 'const_value'
type_part = 'type_part'
type_decl_list = 'type_decl_list'
type_definition = 'type_definition'
type_decl = 'type_decl'
array_type_decl = 'array_type_decl'
field_decl_list = 'field_decl_list'
field_decl = 'field_decl'
name_list = 'name_list'
simple_type_decl = 'simple_type_decl'
var_part = 'var_part'
var_decl_list = 'var_decl_list'
var_decl = 'var_decl'
routine_part = 'routine_part'
function_decl = 'function_decl'
function_head = 'function_head'
procedure_decl = 'procedure_decl'
procedure_head = 'procedure_head'
parameters = 'parameters'
para_decl_list = 'para_decl_list'
para_type_list = 'para_type_list'
var_para_list = 'var_para_list'
routine_body = 'routine_body'
stmt_list = 'stmt_list'
stmt = 'stmt'
non_label_stmt = 'non_label_stmt'
assign_stmt = 'assign_stmt'
proc_stmt = 'proc_stmt'
compound_stmt = 'compound_stmt'
if_stmt = 'if_stmt'
else_clause = 'else_clause'
repeat_stmt = 'repeat_stmt'
while_stmt = 'while_stmt'
for_stmt = 'for_stmt'
direction = 'direction'
case_stmt = 'case_stmt'
case_expr_list = 'case_expr_list'
case_expr = 'case_expr'
goto_stmt = 'goto_stmt'
expression_list = 'expression_list'
expression = 'expression'
expr = 'expr'
term = 'term'
factor = 'factor'
args_list = 'args_list'
record_type_decl = 'record_type_decl'
